services:
  mysql:
    container_name: mysql
    image: ubuntu/mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kabil@007
      - MYSQL_PASSWORD=kabil@007
      - MYSQL_USER=kabil
      - MYSQL_DATABASE=blog
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
